sonar.projectKey=Stanislav04_GitHub-Actions
sonar.organization=stanislav04

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=GitHub-Actions
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=app

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/*.java
